# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RCSceneExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RCSceneExample
  
  # IM
  pod 'RongCloudIM/IMLib', '5.1.8'
  pod 'RongCloudIM/IMKit', '5.1.8'
  
  # RTC
  pod 'RongCloudRTC/RongRTCLib', '5.1.16.1'
  pod 'RongCloudRTC/RongRTCPlayer', '5.1.16.1'
  
  # Lib
  pod 'RCSceneVideoRoom', :path => '../'
  pod 'RCLiveVideoLib', :path => '../../rclivevideolib-ios'
  
end
