# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

inhibit_all_warnings!

target 'RCSceneExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RCSceneExample
  
  # IM
  pod 'RongCloudIM/IMLib', '~> 5.2.0'
  
  # RTC
  pod 'RongCloudRTC/RongRTCLib', '~> 5.2.0'
  pod 'RongCloudRTC/RongRTCPlayer', '~> 5.2.0'
  
  # Lib
  pod 'RCSceneVideoRoom', :path => '../'
  
  pod 'RCLiveVideoLib', :path => '../../rclivevideolib-ios'
  
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  end
 end
end
